amplitude/Amplitude-Java

- src/demo/java/com/amplitude/DemoController.java
- src/main/build.gradle
- src/main/java/com/amplitude/Amplitude.java
- src/main/java/com/amplitude/AmplitudeLog.java
- src/main/java/com/amplitude/Constants.java
- src/main/java/com/amplitude/Event.java
The changes that we discussed to make a more generic server side API
> Backend fixes

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/Question.md
- .github/workflows/jira-issue-create.yml
The templates were copied over from the other SDKs.
> Add automatic GitHub issues for Java SDK

- settings.gradle
- src/demo/java/com/amplitude/DemoController.java
- src/main/java/com/amplitude/Amplitude.java
- src/main/java/com/amplitude/AmplitudeLog.java
- src/main/java/com/amplitude/Constants.java
- src/main/java/com/amplitude/Event.java
Like we discussed, we batch events and send them
1) When there are enough elements in the buffer
2) A certain amount of time (0-10 seconds) has passed after an event has been sent, and we are not flushing
3) Retry events on 500 code (Alyssa @yuhao900914 , please implement the part where it splits the events, and make sure the retry logic makes sense)
Getting feedback early this time
> Event buffering basic logic

- gradle.properties
- src/main/java/com/amplitude/Constants.java
> chore(release): bump up version 1.2.2 for release

- src/main/java/com/amplitude/HttpCall.java
- src/main/java/com/amplitude/Response.java
- src/main/java/com/amplitude/Status.java
Fixes [AMP-37687](https://amplitude.atlassian.net/browse/AMP-37687)
* [ X ] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-iOS/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
* Does your PR have a breaking change?:  No
> fix: Status codes minor issues

- .github/pull_request_template.md
- src/main/java/com/amplitude/Amplitude.java
- src/main/java/com/amplitude/Retry.java
- src/test/build.gradle
- src/test/java/com/amplitude/AmplitudeLogTest.java
- src/test/java/com/amplitude/AmplitudeTest.java
- src/test/java/com/amplitude/EventTest.java
- src/test/java/com/amplitude/HttpCallTest.java
- src/test/java/com/amplitude/RetryTest.java
- src/test/java/com/amplitude/StatusTest.java
- src/test/java/com/amplitude/util/EventsGenerator.java
- src/test/java/com/amplitude/util/MockHttpsURLConnectionHelper.java
- src/test/java/com/amplitude/util/MockURLStreamHandler.java
> test: add unit tests

- src/main/java/com/amplitude/Amplitude.java
- src/main/java/com/amplitude/BatchHttpCall.java
- src/main/java/com/amplitude/GeneralHttpCall.java
- src/main/java/com/amplitude/HttpCall.java
- src/test/java/com/amplitude/AmplitudeTest.java
- src/test/java/com/amplitude/HttpCallTest.java
> feat: add setServerUrl api

- src/main/java/com/amplitude/Amplitude.java
- src/main/java/com/amplitude/HttpTransport.java
- src/test/java/com/amplitude/AmplitudeMultiThreadTest.java
- src/test/java/com/amplitude/HttpTransportTest.java
- src/test/java/com/amplitude/ResponseUtil.java
- Fix issues for multi-threading case
- Set up some unit tests to help catch possible issues.
- Gathering thoughts or suggestions on the fixes or potential issues.
> fix: thread-safe improvements

- src/main/java/com/amplitude/Amplitude.java
- src/test/java/com/amplitude/AmplitudeTest.java
support event upload threshold and period millis settings
* Does your PR have a breaking change?: No
> feat: support event upload threshold and period millis settings

- .github/workflows/pull-request-test.yml
- src/demo/java/com/demo/amplitude/DemoController.java
- src/main/java/com/amplitude/Amplitude.java
- src/main/java/com/amplitude/Event.java
- src/main/java/com/amplitude/HttpTransport.java
- src/test/java/com/amplitude/AmplitudeTest.java
add backs on event level
* Does your PR have a breaking change?: no
> feat: support event with callback

- src/main/java/com/amplitude/Amplitude.java
1. Make logEvent and flushEvents method not synchronized since logEvent handle middleware process. Use lock object instead.
2. Make scheduleFlushEvent method synchronized to prevent creation of multiple flush threads.
* [ X] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-Java/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?
> perf: Client concurrency change

- src/demo/README.md
disclosure for the RCE for just the demo app
> docs: Create README.md

- src/main/java/com/amplitude/Amplitude.java
- src/main/java/com/amplitude/HttpTransport.java
add setLogger() interface to set customized logger for client.
> feat: Support set custom logger for client

- src/main/java/com/amplitude/Amplitude.java
- src/main/java/com/amplitude/AmplitudeLog.java
- src/main/java/com/amplitude/Event.java
- src/main/java/com/amplitude/HttpTransport.java
- src/test/java/com/amplitude/AmplitudeLogTest.java
- src/test/java/com/amplitude/AmplitudeMultiThreadTest.java
- src/test/java/com/amplitude/AmplitudeTest.java
- src/test/java/com/amplitude/HttpTransportTest.java
Add more logs when catching exception
trigger call backs when catching exception
Add setFlushTimeout method
Add shutdown interface to close client and release resources
> feat: Add timeout and cleanUp to Amplitude client

- .github/workflows/jira-issue-create.yml
> chore: update jira creation github action

- src/main/java/com/amplitude/Amplitude.java
- src/main/java/com/amplitude/Event.java
- src/test/java/com/amplitude/AmplitudeTest.java
- src/test/java/com/amplitude/EventTest.java
This reverts commit c87439673ddcab22868cde8be53047b9a7d4dc31.
* Does your PR have a breaking change?:  No
> revert: "feat: add library context field (#76)"

- src/demo/build.gradle
- src/main/build.gradle
Update json dependency to the latest version with the most adoption.
> chore: update json dependency

- src/main/java/com/amplitude/HttpTransport.java
- src/test/java/com/amplitude/AmplitudeMultiThreadTest.java
- src/test/java/com/amplitude/AmplitudeTest.java
- src/test/java/com/amplitude/HttpTransportTest.java
https://amplitude.atlassian.net/browse/AMP-78787
429 response should indicate that we need to slow down and should retry
> fix: Should retry 429

- src/main/java/com/amplitude/AmplitudeLog.java
- src/test/java/com/amplitude/AmplitudeLogTest.java
Add the getter method for logLevel and logMode.
Related to [this](https://github.com/amplitude/Amplitude-Java/issues/93) request.  
> feat: support setter for logMode and logLevel

- .github/workflows/pull-request-test.yml
- src/test/java/com/amplitude/HttpTransportTest.java
- Increase test timeout so that it passes in github actions
> chore: Fix failing test in github actions

- README.md
No real change. Just adding a minor change to the readme to force release a new version of the SDK
> fix: Updating readme to force release a new version

- src/demo/build.gradle
- src/main/build.gradle
- src/test/build.gradle
Updating org json version and making them in sync across all projects
Fix for issue - #99 
> fix: Update org json version to fix CVE-2023-5072

- README.md
No real change. Pushing a change to update package version
> fix: Manually pushing a version update
